version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quanly
      MYSQL_USER: user
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    image: php:8.2-cli
    container_name: laravel_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: quanly
      DB_USERNAME: user
      DB_PASSWORD: password
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge